### PR TITLE
Upgrade to SONiC 202205 

### PR DESCRIPTION
**Pull request by ksandeep-palc**

### CODE REVIEW

**Comment by ishidawataru** [comment]
@ksandeep-palc Thanks. Please clean up the commits.
Also, let's use the following for git use info.

> git config user.name "Goldstone"
> git config user.email "goldstone-nos@googlegroups.com"

**Comment by ksandeep-palc** [comment]
@ishidawataru - we need to generate an image based on the changes in this PR and build the usonic-debug:202205 image and push to ghcr.io, this will allow me to do a full build in goldstone-buildimage. With these changes the system is coming up and is stable, and I am able to do interface no-shut from gscli and the same is getting reflected in bcmsh 'ps' output, so we are good.

**Comment by ksandeep-palc** [comment]
@ishidawataru please also merge - https://github.com/microsonic/sonic-buildimage/pull/1 I am not able to add either tag you or add you as reviewer in that PR.

**Comment by ishidawataru** [comment]
@ksandeep-palc Have you already built an image based on these changes?

**Comment by ksandeep-palc** [comment]
> @ksandeep-palc Have you already built an image based on these changes?

Yeah @ishidawataru I have build an INSTALLER image based on these changes.

**Comment by ishidawataru** [comment]
@ksandeep-palc That's nice. Are you using the [sm-sonic-202205](https://github.com/oopt-goldstone/goldstone-buildimage/tree/sm-sonic-202205) branch to build the image? Does `goldstone-buildimage` repo need any modification other than sonic-buildimage submodule update to accomodate the changes in this PR?

**Comment by ishidawataru** [comment]
@ksandeep-palc Please fix the conflicts.

**Comment by ksandeep-palc** [comment]
> @ksandeep-palc Please fix the conflicts.

@ishidawataru Sorry I dint get what conflicts we are referring to, I don't see any conflicts in this PR

**Comment by ksandeep-palc** [comment]
> > @ksandeep-palc Please fix the conflicts.
> 
> @ishidawataru Sorry I dint get what conflicts we are referring to, I don't see any conflicts in this PR

OK you are referring to goldstone-buildimage PR conflicts.

**Comment by ishidawataru** [comment]
@ksandeep-palc This repo uses `rebase and merge` policy to merge the PR. This branch cannot be rebased due to conflicts. Please do `git rebase origin/202205` on this branch and fix the conflicts.

**Comment by ksandeep-palc** [comment]
@ishidawataru Please see if this can be merged now, else will have to do it similar to goldstone-buildimage PR.

**Comment by ishidawataru** [comment]
@ksandeep-palc opened #14. I think the problem comes from several merge commits in this PR. I think you need to put your commits on top of the target branch (`202205`) instead of merging the target branch into the branch that contains your commits.

**Comment by ishidawataru** [comment]
closed by #14

**Pull request closed without merging**
